### ISSUE TITLE
process_document_sample_v1beta3 failed with "Request contains an invalid argument."

### ISSUE THREAD

**Issue by felix-zg** [googleapis/python-documentai#49]
#### Environment details

  - OS type and version: Mac 10.15.6
  - Python version: 3.7.8
  - pip version:  20.2.4
  - `google-cloud-documentai` version: 0.3.0

#### Steps to reproduce

  1. Running process_document_sample_v1beta3.py with /resources/invoice.pdf
  2. Processor in EU

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Request contains an invalid argument."
	debug_error_string = "{"created":"@1603381610.907626000","description":"Error received from peer ipv6:[x:x:x:x::x]:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Request contains an invalid argument.","grpc_status":3}"
>
```

Thanks!

**Comment by munkhuushmgl** [comment]
@felix-zg Have u tried changing the endpoint to EU ?

**Comment by munkhuushmgl** [comment]
By default endpoint = us

https://github.com/googleapis/python-documentai/blob/cc8c58d1bade4be53fde08f6a3497eb3f79f63b1/google/cloud/documentai_v1beta3/services/document_processor_service/client.py#L117

**Comment by edumotya** [comment]
Yes @felix-zg @munkhuushmgl, changing the DEFAULT_ENDPOINT does the trick. You can apply the following workaround for eu:

```python
from google.cloud import documentai_v1beta3 as documentai

class DocumentProcessorServiceClientEu(documentai.DocumentProcessorServiceClient):
    DEFAULT_ENDPOINT = "eu-documentai.googleapis.com"

client = DocumentProcessorServiceClientEu()
```

**Comment by munkhuushmgl** [comment]
Thanks @edumotya 

With that note, I am closing this issue.

If you are still having this issue, feel free to reopen.

**Comment by telpirion** [comment]
@edumotya , FYI the best practice for changing the endpoint is this:

```
client_options = { 'api_endpoint': 'eu-documentai.googleapis.com'  }
client = documentai.DocumentProcessorServiceClient(client_options=client_options)
```
