### ISSUE TITLE
google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.

### ISSUE THREAD

**Issue by postak** [googleapis/python-documentai#77]
I get error trying examples code (both online and offline processing). Same error 

#### Environment details

  - OS type and version: OSX 11.1
  - Python version: 3.8.2
  - pip version: 19.2.3
  - `google-cloud-documentai` version: 0.3.0

#### Steps to reproduce

  python3 parse_from_gs_beta3.py

#### Code example

the example in https://github.com/googleapis/python-documentai/blob/master/samples/snippets/batch_process_documents_sample_v1beta3.py 

#### Stack trace
```
Traceback (most recent call last):
  File "/Users/postak/Library/Python/3.8/lib/python/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/postak/Library/Python/3.8/lib/python/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/postak/Library/Python/3.8/lib/python/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Request contains an invalid argument."
	debug_error_string = "{"created":"@1609844424.988576000","description":"Error received from peer ipv4:216.58.208.170:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Request contains an invalid argument.","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "parse_from_gs_beta3.py", line 103, in <module>
    batch_process_documents(project_id='my-prj', location='eu', processor_id='cd6.....', gcs_input_uri='gs://my-bucket/file.pdf', gcs_output_uri='gs://my-bucket/', gcs_output_uri_prefix='doc_ai_out')
  File "parse_from_gs_beta3.py", line 41, in batch_process_documents
    operation = client.batch_process_documents(request)
  File "/Users/postak/Library/Python/3.8/lib/python/site-packages/google/cloud/documentai_v1beta3/services/document_processor_service/client.py", line 411, in batch_process_documents
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Users/postak/Library/Python/3.8/lib/python/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/postak/Library/Python/3.8/lib/python/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/Users/postak/Library/Python/3.8/lib/python/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/postak/Library/Python/3.8/lib/python/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.```

**Comment by postak** [comment]
it seems that the problem occurs only with location = 'eu'

**Comment by munkhuushmgl** [comment]
@postak How are you passing your params? 
Have you confirmed that changing 'us' location works fine on your end?

**Comment by postak** [comment]
yes, I have obfuscated my parameters. 
I confirm that with a processor created in us it works and with one eu it fails.
I have double checked right now

**Comment by munkhuushmgl** [comment]
Looks like you are missing the part of changing endpoint on client options

```
client_options = {"api_endpoint": "eu-documentai.googleapis.com"}
client = documentai.DocumentProcessorServiceClient(client_options=client_options)
```

**Comment by munkhuushmgl** [comment]
Feel free to reopen this issue if you are experiencing any other problem.
Changing the endpoint will fix the problem.

**Comment by munkhuushmgl** [comment]
I was able to repro your error 
![image](https://user-images.githubusercontent.com/45373284/103683919-a550c500-4f3f-11eb-9f1f-29879074c12b.png)

**Comment by postak** [comment]
ok. it works!!! thanks.
I suggest to add those two lines in the code example otherwise is difficult to guess for those connecting from europe ... ;)
